FROM condaforge/mambaforge

LABEL base.image="ubuntu:mambaforge"
LABEL dockerfile.version="1"
LABEL software="Networkx and utilities"
LABEL software.version="3.2.1"
LABEL description="Networkx and utilities for plotting and analysis"
LABEL website="https://networkx.org/"

RUN apt-get update && apt-get install -y --no-install-recommends \
  tree

RUN tree -L 3

COPY environment.yml .
RUN /bin/bash -c "mamba env update -n base -f environment.yml"
