FROM condaforge/mambaforge

LABEL base.image="ubuntu:mambaforge"
LABEL dockerfile.version="1"
LABEL software="Polars and utilities"
LABEL software.version="1.1.0"
LABEL description="Polars, Pandas and PyArrow"
LABEL website="https://pola.rs/"

RUN apt-get update && apt-get install -y --no-install-recommends \
  tree

RUN tree -L 3

COPY environment.yml .
RUN /bin/bash -c "mamba env update -n base -f environment.yml"
