FROM condaforge/mambaforge

LABEL base.image="ubuntu:mambaforge"
LABEL dockerfile.version="1"
LABEL software="SNP-it"
LABEL software.version="1.0.0"
LABEL description="SNP-it for MTB lineage classification"
LABEL website="https://github.com/philipwfowler/snpit"

RUN apt-get update
RUN apt-get install -y build-essential autoconf wget git autoconf zlib1g-dev libbz2-dev liblzma-dev libncurses-dev
COPY environment.yml .
RUN /bin/bash -c "mamba env update -n pipeline_env -f environment.yml" && \
  echo "source activate pipeline_env" >> ~/.bashrc && \
  /bin/bash -c "source activate pipeline_env"
RUN git clone https://github.com/philipwfowler/snpit.git && \
  cd snpit && \
  python3 setup.py install