FROM condaforge/mambaforge

LABEL base.image="ubuntu:mambaforge"
LABEL dockerfile.version="1"
LABEL software="fast-lineage-caller"
LABEL software.version="0.3.1"
LABEL description="Software to identify Mtb lineage"

RUN apt-get update && apt-get install -y --no-install-recommends \
  tree

RUN tree -L 3

COPY environment.yaml .
RUN /bin/bash -c "mamba env update -n base -f environment.yaml"
