FROM python:3.7

LABEL base.image="ubuntu:mambaforge"
LABEL dockerfile.version="1"
LABEL software="fast-lineage-caller"
LABEL software.version="0.3.1"
LABEL description="Software to identify Mtb lineage"

pip install fast-lineage-caller
