FROM condaforge/mambaforge

LABEL base.image="ubuntu:mambaforge"
LABEL dockerfile.version="1"
LABEL software="Checkm-genome"
LABEL software.version="1.1.3"
LABEL description="Assess the quality of microbial genomes recovered from isolates, single cells, and metagenomes"
LABEL website="https://github.com/Ecogenomics/CheckM"
LABEL license="https://github.com/Ecogenomics/CheckM/blob/master/LICENSE"

RUN apt-get update && apt-get install -y --no-install-recommends \
  tree

RUN tree -L 3

COPY environment.yaml .
RUN /bin/bash -c "mamba env update -n base -f environment.yaml"
