FROM condaforge/mambaforge

LABEL base.image="ubuntu:mambaforge"
LABEL dockerfile.version="1"
LABEL software="SPAdes + auxiliary tools"
LABEL software.spades.version="3.15.3"
LABEL software.seqtk.version="1.3"
LABEL description="SPAdes assembler with seqtk and gawk included for filtering of contigs"

COPY environment.yml .
RUN /bin/bash -c "mamba env update -n base -f environment.yml"
