# This workflow is based on part of the staphb workflow at https://github.com/StaPH-B/docker-builds/blob/master/.github/workflows/build-to-deploy.yml

name: Build and deploy image

on:
  workflow_dispatch:
    inputs:
      path_to_context:
        required: true
        type: string
      dockerfile_name:
        default: Dockerfile
        required: false
        type: string
      REGISTRY:
        default: ghcr.io
        required: false
        type: string
      IMAGE_NAME:
        required: true
        type: string
      tag:
        required: false
        default: latest
        type: string
      push_latest_tag:
        default: true
        required: false
        type: boolean

jobs:

  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ${{ env.REGISTRY }}/${{ inputs.IMAGE_NAME }}:${{ inputs.tag }}
            ${{ env.REGISTRY }}/${{ inputs.IMAGE_NAME }}:latest

      - name: Build and push user-defined tag to DockerHub
        id: docker_build_user_defined_tag
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.path_to_context }}
          file: ${{ inputs.path_to_context }}/${{ inputs.dockerfile_name }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: | # pushing to dockerhub for only the user-defined inputs.tag
            ${{ inputs.REGISTRY }}/${{ inputs.container_name }}:${{ inputs.tag }}

      - name: Build and push latest tag to DockerHub
        id: docker_build_latest_tag
        uses: docker/build-push-action@v3
        if: ${{ inputs.push_latest_tag }}
        with:
          context: ${{ inputs.path_to_context }}
          file: ${{ inputs.path_to_context }}/${{ inputs.dockerfile_name }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: | # pushing to dockerhub for only latest tag
            ${{ inputs.REGISTRY }}/${{ inputs.container_name }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
